### ISSUE TITLE
Overwriting array properties.

### ISSUE THREAD

**Issue by bobrenjc93** [sindresorhus/deep-assign#13]
Is this intended behavior?

``` js
deepAssign({a: [1]}, {a: []}) => Object {a: Array[1]}
```

Based on the behavior of `Object.assign` (this module is just a recursive version of it correct?), I would have assumed it should have returned `Object {a: Array[0]}`

**Comment by schnittstabil** [comment]
@bobrenjc93  In my opinion that is the expected behavior, because we _**Recursively** Object.assign()_:

``` js
deep_assign({a: [1]}, {a: []})

// should be similar to
{a: deep_assign([1], [])}

// which have to be the same as 
{a: Object.assign([1], [])}
```

(If `Object {a: Array[1]}` means `{a: [1]}`)

This is consistent to the [current `undefined` behavior](https://github.com/sindresorhus/deep-assign/issues/12#issuecomment-170815832).

**Comment by bobrenjc93** [comment]
I completely understand the recursive nature of this function. The question is what should be the base case. In my opinion, I think it only makes to recurse further if the value is a true object and not an array. In the event the value is not an object, the recursion should halt and behave the same way you'd expect a non recursive Object.assign for that particular value. 

Perhaps it would be good to have the context under which this module was developed. I'm currently trying to use this module for a redux application and the behavior I described above was what I would expect in a recursive Object.assign module.

**Comment by schnittstabil** [comment]
> I think it only makes to recurse further if the value is a _true object_ and not an array.

_True Object_ is the crux of the matter: e.g Javascript also considers functions to be objects, and there seems no generally accepted definition for _True Objects_.

[npm](https://www.npmjs.com/) and [bower](http://bower.io/search) contain myriad packages for merging/extending/… objects – most of them without a precise semantic. If you agree with me that [Plain Objects](https://github.com/sindresorhus/is-plain-obj) are the one and only _True Objects_, [schnittstabil/merge-options](https://github.com/schnittstabil/merge-options) may meet your requirements.

As [`Object.assign`](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign) does not distinguish `Objects` and `Arrays` I see no justification to do so in `deep-assign`.

**Comment by bobrenjc93** [comment]
Ah okay makes sense. merge-options is exactly what I need, I'll go use that. Thanks!
