### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by Salakar** [sindresorhus/deep-assign#14]
Just a thought, but this couldn't this be simplified a lot more with ES6?

Here's what I was able to come up with:  https://gist.github.com/Salakar/1d7137de9cb8b704e48a

**Comment by schnittstabil** [comment]
Thank you for suggestion, but I don't think you spend enough time to get deeply into the project aims. Please take some time and a take look at our [test.js](https://github.com/sindresorhus/deep-assign/blob/master/test.js) to figure out how we expect `deep-assign` to be.

Despite this, your suggestion lacks some essential properties. First of all, this is a node package, thus we cannot use all ES2015 features, like `export` etc. Secondly, your suggestion is not even consistent with `Object.assign`, e.g.: 
1. Parameter and return values
   
   ``` js
   Object.assign({}, {foo:'bar'}, {unicorns: 'many'})
   //=> { foo: 'bar', unicorns: 'many' }
   
   mergeDeep({}, {foo:'bar'}, {unicorns: 'many'})
   //=> undefined
   ```
2. Symbol support
   
   ``` js
   var target = {};
   Object.assign(target, {[Symbol.for('foo')]: 'bar'});
   target[Symbol.for('foo')]
   //=> 'bar'
   
   var target = {};
   mergeDeep(target, {[Symbol.for('foo')]: 'bar'});
   target[Symbol.for('foo')]
   //=> undefined
   ```
3. Functions and Arrays are Objects too
   
   ``` js
   var target = () => 42;
   Object.assign(target, { foo: 'bar' });
   target.foo
   //=> 'bar'
   
   var target = () => 42;
   mergeDeep(target, { foo: 'bar' });
   target.foo
   //=> undefined
   ```
