### ISSUE TITLE
Does not work with sealed objects

### ISSUE THREAD

**Issue by nhardy** [sindresorhus/deep-assign#2]
See ES6 Code below:

```
class Model {
  constructor(props) {
    this.init();

    Object.seal(this);

    if (props) {
      deepAssign(this, props);
    }
  }

  init() {
    Object.defineProperties(this, {
      one: {
        value: null,
        writable: true,
        enumerable: true
      },
      two: {
        value: {},
        writable: true,
        enumerable: true
      }
    });
    Object.defineProperties(this.two, {
      three: {
        value: null,
        writable: true,
        enumerable: true
      },
      four: {
        value: null,
        writable: true,
        enumerable: true
      }
    });
  }
}

console.log(new Model({one: 'foo', two: {three: 'bar', four: 'baz', five: 'shouldn\'t appear'}, six: 'won\'t appear'}));
```

**Comment by sindresorhus** [comment]
What exactly is not working? What did you expect? Please provide a simpler example, preferably a failing test.

**Comment by schnittstabil** [comment]
@nhardy Your code works exactly as intended:
1. [`Object.seal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) preventing `six` from being added
2. [`Object.seal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) marking `two` as non-configurable, but that does not mean you can't add a new property to `two` (see [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) for details about configurable)
