### ISSUE TITLE
What is the difference deep assigning with JSON.parse?

### ISSUE THREAD

**Issue by inancgumus** [sindresorhus/deep-assign#20]
``` javascript
let deepClone = JSON.parse(JSON.stringify(objectToBeCloned))
```

The speed maybe? About speed: http://stackoverflow.com/a/5344074/115363

Or JSON is just for simple objects?

**Comment by sindresorhus** [comment]
Different concepts. The above is actually cloning the object. This module assigns properties of an object to a new or existing object. I would Google how `Object.assign()` works.
