### ISSUE TITLE
Assigning an array shorter than previous one results in merged array

### ISSUE THREAD

**Issue by JonnyBurger** [sindresorhus/deep-assign#21]
I have encountered this problem when I tried to remove an object from an array and re-assign it to an object.

I have broken down the problem into this simple example:

``` js
const deepAssign = require('deep-assign');

const result = deepAssign({}, {
  a: [1, 2]
}, {
  a: [3]
});
console.log(result.a) // => [3, 2]
```

I expected `result.a` to be `[3]` instead.
The native `Object.assign` from v8 yields a different result:

``` js
const result = Object.assign({}, {
  a: [1, 2]
}, {
  a: [3]
});
console.log(result.a) // => [3]
```

This leads me to believe that this is a bug in `deep-assign`.

**Comment by schnittstabil** [comment]
`deep-assign` is recusive, thus the base case of your example should be:

``` js
Object.assign([1, 2], [3])
//=> [ 3, 2 ]
```

**Comment by sindresorhus** [comment]
This module is now deprecated: https://github.com/sindresorhus/deep-assign/commit/b3320626909f7b60c06292b09f6b025488374f97
