### ISSUE TITLE
deep assign and functions

### ISSUE THREAD

**Issue by belgac** [sindresorhus/deep-assign#22]
Hello,

When i try using deep-assign on an object referencing functions i get strange results.

Here is my example:
```js
var deepAssign = require('deep-assign');
function test1() {
    console.log('test1')
};

function test2() {
    console.log('test2')
};

var classic = Object.assign(
    {
        a:test1,
    },{
        a:test2
    }
);
var deep = deepAssign(
    {
        a:test1,
    },{
        a: test2,
    }
);

console.log('classic assign' ,classic); // should be { a: test2 } and is { a: test2 }
console.log('deep assign', deep); // should be { a: test2 } but is { a: test1 }
console.log('is property a equal in classic and deep?', classic.a === deep.a) // should be true but is false
```

You can test this code here: https://runkit.com/belgac/582475d188bb01001414cdc5

Is this normal or should this be fixed?

**Comment by schnittstabil** [comment]
`deep-assign` is recursive, thus the base case of your example would be:

``` js
var classic = Object.assign(test1, test2);
classic();
// outputs 'test1'
```

> Is this normal or should this be fixed?

IMO, changing this would lead to unexpected behavior. E.g.

``` js
var classic = Object.assign({}, test2);
classic();
//=> TypeError: classic is not a function

// Thus, IMO, the following should also throw a TypeError:
var deep = deepAssign({a:{}}, {a:test2});
deep.a();
```

See also https://github.com/sindresorhus/deep-assign/pull/19#issuecomment-252903594

**Comment by sindresorhus** [comment]
This module is now deprecated: https://github.com/sindresorhus/deep-assign/commit/b3320626909f7b60c06292b09f6b025488374f97
