### ISSUE TITLE
Why should this module not be used?

### ISSUE THREAD

**Issue by saibotsivad** [sindresorhus/deep-assign#26]
The github description says `[DON'T USE THIS MODULE PLEASE]` but the readme doesn't say why not, and looking at the open issues doesn't make it clear either.

It would be good to put a sentence or two in the readme that says what's wrong with the module.

**Comment by ben-turner** [comment]
+1

**Comment by kevva** [comment]
Partly because of https://github.com/sindresorhus/deep-assign/issues/6.

**Comment by sindresorhus** [comment]
Explained here: https://github.com/sindresorhus/deep-assign/commit/b3320626909f7b60c06292b09f6b025488374f97
