### ISSUE TITLE
Can you add a param(value) which is equal undefined during assigning

### ISSUE THREAD

**Issue by yang123guo** [sindresorhus/deep-assign#28]
now:
`
deepAssign({a: {b: 0}}, {a: {b: 1, c: 2}}, {a: {c: 3}}); 
 //=> {a: {b: 1, c: 3}}
deepAssign({a: {b: 0}}, {a: {b: 1, c: 2}}, {a: {c: 3, b: undefined}});  
//=> {a: {b: 1, c: 3}}
`
if  (b ===  ' ' ||  0  ||  false) 
deepAssign({a: {b: 0}}, {a: {b: 1, c: 2}}, {a: {c: 3, b:   ''   }});  
//=> {a: {b: 1, c: 3}}
not 
//=> {a: {b:  '' , c: 3}}

we can add any param regard as undefined
Thank you!

**Comment by sindresorhus** [comment]
This module is deprecated.
