### ISSUE TITLE
Incorrectly assign object with function as value

### ISSUE THREAD

**Issue by fduch2k** [sindresorhus/deep-assign#5]
Instead of provider: function... - received provider: {}

> console.log(assign({data:{test:1}}, {data:{provider:function() {}, test:2}}));
>    { data: { test: 2, provider: {} } }

**Comment by ruffle1986** [comment]
@fduch2k yes, it's an oldie. it's already fixed in the latest major version. Use `deep-assign` 2.0.0.

``` sh
$ npm i -S deep-assign@latest
```

**Comment by fduch2k** [comment]
thx
