### ISSUE TITLE
Regression in 2.0.0

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/deep-assign#6]
This commit https://github.com/sindresorhus/deep-assign/commit/b55d7b6691c83e7ad751452b9e04aadfe718c702 seems to cause problem in [XO](https://github.com/sindresorhus/xo/commit/35aaec846e6858c5c70e1ffdfa0c78f43037a85d).

I've added a failing test: https://github.com/sindresorhus/deep-assign/commit/efa61abbee1593fdfa1ce619017f507ebc7d405c

It seems at deep level it no longer creates a new object but reuses the existing one.

@schnittstabil Could you take a look?

**Comment by schnittstabil** [comment]
That happens, because we do not recurse into objects in v2, which may be configurable by introducing options (as discussed in #4):

``` js
    const fixture = {
        foo: {
            bar: false
        }
    };

    const run = x => {
        const opts = fn({}, fixture);
        //=> opts.foo === fixture.foo

        if (x === true) {
            opts.foo.bar = true;
            //=> opts.foo.bar === fixture.foo.bar === true
        }

        return opts.foo.bar;
    };

    t.true(run(true));
    //=> fixture.foo.bar === true
    t.false(run());
```

**Comment by sindresorhus** [comment]
> we do not recurse into objects in v2

I must have missed that in the original discussion... But what's the point then of _deep_ assign, if it doesn't assign deeply? It should really be the default behavior.

**Comment by schnittstabil** [comment]
deep-assign recurses, if there is a corresponding target property:

``` js
function User(name) {
  this.name = name;
}

var target = {
    user: new User('Alice')
};

var source = {
    user: new User('Bob')
};

// target.user exists, so deep-assign steps into target.user and source.user:
deepAssign(target, source);
//=> target.user.name === source.user.name === 'Bob'
// but: target.user !== source.user
```

However, deep-assign simply sets the target property, if there is no corresponding property:

``` js
var target = {
};

var source = {
    user: new User('Bob')
};

deepAssign(target, source);
//=> target.user === source.user
```

The reason for this is that we can not clone arbitrary source objects in a sensible way, e.g. objects with a prototype chain. (Also functions are objects too.)

**Comment by schnittstabil** [comment]
deep-assign is used as a _option-merge-tool_ in XO. I think that will sooner or later be in conflict with deep-assigns main intention:

> Recursive Object.assign()

An example:

``` js
const DEFAULT_CONFIG = {
  filter: () => true,
};

const opts = {
  filter: n => n % 2,
};

var config = deepAssign(DEFAULT_CONFIG, opts);
//=> config.filter === DEFAULT_CONFIG.filter
```

That's because all properties of `opts.filter` are copied to `DEFAULT_CONFIG.filter` :unamused:

I would suggest to create a new project for this, with defaults like array-slicing, _plain-object_-cloning, function-overwriting etc. I would be happy to help.

**Comment by schnittstabil** [comment]
@sindresorhus I started working on a  _option-merge-tool_

**Comment by ruffle1986** [comment]
what's the problem with this? https://www.npmjs.com/package/deep-extend

**Comment by schnittstabil** [comment]
@ruffle1986 For most use cases: nothing - But I want some other semantics, e.g. the following doesn't seems reasonable to me: 

``` js
deepExtend({}, {p: Promise.resolve(42)})
//=> { p: {} }
```

**EDIT**: But most importantly `deep-extends` [copies buffers](https://github.com/unclechu/node-deep-extend/blob/9ea374c54bdff7e42be163ae09670ea8cf3bbc7e/lib/deep-extend.js#L41) - I think that is not very sensible for merging options.

**Comment by schnittstabil** [comment]
I've just published [merge-options](https://github.com/schnittstabil/merge-options), which is based on is-plain-obj.
@sindresorhus @ruffle1986 @coderhaoxin @sugarshin: reviews, comments and feature request are welcome

**Comment by etiktin** [comment]
I was trying to use deep-assign to merge a user provided options object with my defaults and encountered an issue similar to this https://github.com/sindresorhus/deep-assign/issues/6#issuecomment-152298779 (function from defaults wasn't replaced by the function from options). Ended up, trying out [merge-options](https://github.com/schnittstabil/merge-options) and it worked well for me.
I think the readme should contain some examples of the edge cases and a link to merge-options in the related section.

**Comment by davej** [comment]
Yeah, I got caught by this also.

Probably should have been more vigilant but a quick mention of the issue might be useful in the Readme since it arguably deviates from the description of "Recursive Object.assign()".

**Comment by sindresorhus** [comment]
This module is now deprecated: https://github.com/sindresorhus/deep-assign/commit/b3320626909f7b60c06292b09f6b025488374f97
