### ISSUE TITLE
test fails: support symbols as targets

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/deep-assign#9]
```
  ✖ support symbols as targets
  t.is(target.sym.constructor, Symbol)
                  |            |      
                  #function#   #function#
```

**Comment by Kreozot** [comment]
Oops. Just create the duplicate issue.

**Comment by Kreozot** [comment]
Here is my point: The problem is only when using ava 0.5.0.
But if you use ava 0.3.0 the check is pass successfully.

Is this problem on ava side? If so, then I think we need to specify ava version in package.json, create issue in ava repo and refer to this issue.
